[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10
[[main]]
  name = "Tech"
  pageRef = "tech"
  weight = 20
[[main]]
  name = "Notes"
  pageRef = "notes"
  weight = 30
[[main]]
  name = "Daily"
  pageRef = "daily"
  weight = 40
[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 50
[[main]]
  name = "About"
  pageRef = "about"
  weight = 60
[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10
[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20
[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 30
[[footer]]
  name = "GitHub"
  url = "https://github.com/AquariniqueMu"
  weight = 40
