name: Hugo build and deploy

on:
  push:
    branches: [ main ]  # 当向 main 分支推送代码时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) 检出 main 分支（Hugo 源码）
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: true  # 如果你的主题是 git submodule，需要这个，否则可以去掉

      # 2) 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # 3) 构建
      - name: Build
        run: hugo --minify

      # 4) 部署到 gh-pages 分支
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          # force_orphan: true  # 如果希望每次都用全新提交，可打开此项
